    Version="1"

    [[command]]
      name = "basic command"  # name of the command
      isTemplate = true       # this command can be used as a template, no command will be created
      addGroups = true        # add current systems groups  (linux only)
      impersonate = true      # use executing user and group for execution in the container (linux only)
      workDir = "${PWD}"        # define working directory
      removeContainer=true    # remove container after command has finished
      isInteractive=true      # enable interaction with the called command
      RequireEnvVars=true    # if true, not defined env vars that are configured will lead to an error

      # volume mappings
      volumes = [
	  "${PWD}:${PWD}",
          "${HOME}:${HOME}",
          "${SSH_AUTH_SOCK}:/run/ssh.sock",
          "/etc/passwd:/etc/passwd:ro",
          "/etc/group:/etc/group:ro",
	  "/tmp/.X11-unix:/tmp/.X11-unix",
      ]

      # environment variable mappings
      envvars = [
	  "PWD=${PWD}",
          "HOME=${HOME}",
          "SSH_AUTH_SOCK=/run/ssh.sock",
      ]

    [[command]]
        template = "basic command"
        name = "graphviz"
        image = "fhamroctopus/graphviz"

    [[command]]
        template = "basic command"
        name = "node-cmd"
        entryPoint = "node"
	uniqueNames=true
        image = "node:12.4.0"
        envvars = [
              "PWD=${PWD}",
              "HOME=${HOME}",
              "SSH_AUTH_SOCK=/run/ssh.sock",
        ]

    [[command]]
        template = "basic command"
    	name = "node"
        entryPoint = "node"
    	image = "node:12.4.0"
        envvars = [
              "PWD=${PWD}",
              "HOME=${HOME}",
              "SSH_AUTH_SOCK=/run/ssh.sock",	
        ]
        ports=["9876:9876"]
            portsFromParams = [
                "--inspect-brk=(\\d*)",
                "--inspect=(\\d*)",
            "--port=(\\d*)"
            ]

 [[command]]
        template = "basic command"
        name = "karma"
        uniqueNames=true
        entryPoint = "bash"
        image = "node:8.9.0"
        ip="10.0.0.2"
        network="testnet"


    [[command]]
        template="basic command"
        name="ionic-serve"
        uniqueNames=true
        entryPoint = "node_modules/.bin/ionic"
        image = "node:8.9.0"
        ports=["8200:8200","8100:8100"]

    [[command]]
        template="basic command"
        name="ionic"
        uniqueNames=true
        entryPoint = "node_modules/.bin/ionic"
        image = "node:8.9.0"

    [[command]]
        template = "basic command"
        name = "node-with-chrome"
        entryPoint = "node"
        image = "node-chrome"
	ReuseContainer=true
        envvars = [
		"CHROME_BIN=/usr/bin/google-chrome",
                "_INTELLIJ_KARMA_INTERNAL_PARAMETER_user-config=/home/nils/ownCloud/shared-projects/PhpstormProjects/angular-demo/karma.conf.js",
        ]
        portsFromParams = [
            "--inspect-brk=(\\d*)",
            "--inspect=(\\d*)",
	    "--port=(\\d*)"
        ]


    [[command]]
        template = "basic command"
    	name = "npm"
	uniqueNames=true
    	#impersonate = false
	removeContainer=true
    	entryPoint = "npm"
    	image = "node:12.4.0"

    [[command]]
        template = "basic command"
        name = "npm-test"
        removeContainer=true
	entrypoint="npm"
        command="test"
        image = "protractor:latest"
        envvars = [
          "PWD=${PWD}",
          "HOME=${HOME}",
          "SSH_AUTH_SOCK=/run/ssh.sock",
	     "DISPLAY=unix${DISPLAY}",
        ]

   [[command]]
	template = "basic command"
	name = "ruby"
	entryPoint = "ruby"
	image = "ruby:2.4-jessie"

   [[command]]
        template = "basic command"
        name = "irb"
        entryPoint = "irb"
        image = "ruby:2.4-jessie"

   [[command]]
        template = "basic command"
        name = "gem"
        entryPoint = "gem"
        image = "ruby:2.4-jessie"

   [[command]]
        template = "basic command"
        name = "bb-sh"
        entryPoint = "sh"
        image = "busybox"

  [[command]]
        template = "basic command"
        name = "perl"
        entryPoint = "perl"
        image = "perl:5.20"

  [[command]]
	name = "swagger-editor"
	image = "swaggerapi/swagger-editor"
	isDaemon=true
	isInteractive=false
	impersonate=false
	ports = ["80:8080"]

  [[command]]
	template = "basic command"
        name = "goswagger"
        image = "quay.io/goswagger/swagger"
	envvars = ["GOPATH=${GOPATH}"]
  #
  # PHPStorm integration
  #
  [[command]]
  	isTemplate=true
	name="basic-php-command"
    	entrypoint="php"
    	removeContainer=true
    	impersonate=true
    	workDir="${PWD}"
    	volumes=[
        	"/tmp:/tmp",
	        "/home/nils:/home/nils"
	]
  [[command]]
	removeContainer=true
	isInteractive=true
	impersonate=true
        name="php"
        image="php7.2"
        template="basic-php-command"
	ports=["8000:8000"]
        envvars=[
                "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
        ]
        replaceArgs=[
                [
                        "-dxdebug.remote_host=127.0.0.1",
                        "-dxdebug.remote_host=172.17.0.1",
                ]
        ]

  [[command]]
    	name="php7.2"
    	image="php7.2"
    	template="basic-php-command"
    	envvars=[
        	"XDEBUG_CONFIG=${XDEBUG_CONFIG}"
	]
	replaceArgs=[
        	[
	            	"-dxdebug.remote_host=127.0.0.1",
            		"-dxdebug.remote_host=172.17.0.1",
        	]
	]

  [[command]]
    	name="phpmd"
    	image="php7.2"
    	template="basic-php-command"
    	command="vendor/bin/phpmd"

  [[command]]
   	name="phpcs"
    	image="php7.2"
    	template="basic-php-command"
    	command="vendor/bin/phpcs"

  [[command]]
        name="php7.4"
        image="php7.4"
        template="basic-php-command"
        envvars=[
                "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
        ]
        replaceArgs=[
                [       
                        "-dxdebug.remote_host=127.0.0.1",
                        "-dxdebug.remote_host=172.17.0.1",
                ]
        ]

  [[command]]
	name="jupyter"
	image="jupyter/datascience-notebook"
	addGroups = true     
	impersonate = true    
	removeContainer=true    

	volumes=[
		"${PWD}:/home/jovyan/work",
	]
	environment=[
		"JUPYTER_ENABLE_LAB=yes",
	]


